### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by steffann** [bgpfix/bgpipe#4]
I was just playing with bgpipe, and ran into this:

```
❯ go install github.com/bgpfix/bgpipe@latest
[…]
❯ bgpipe -o -- speaker :179
2024-08-26 10:45:53 INF listening on [::]:179 stage="[2] listen"
2024-08-26 10:45:55 INF connected [::1]:179 -> [::1]:62626 stage="[2] listen"
fatal error: all goroutines are asleep - deadlock!
[…]
```

# Steps to reproduce
- run `bgpipe -o -- speaker :179`
- in another window: `telnet localhost 179`
- close the telnet session (ctrl-], `quit`)
- the bgpipe process crashes with the deadlock message

# Environment
- macOS Sonoma 14.6.1
- Darwin studio.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64
- go version go1.23.0 darwin/arm64

```
❯ bgpipe --version
bgpipe build info:
go	go1.23.0
path	github.com/bgpfix/bgpipe
mod	github.com/bgpfix/bgpipe	v0.8.8	h1:LbZ76zQ9xSWhm5elKOaYWnNJyrRDensYorzT7DEB6uw=
dep	github.com/bgpfix/bgpfix	v0.3.0	h1:Xwd9lkzRP4wF9dzfCXJfMPb7sDJSoBtMrScM2uv9q+g=
dep	github.com/buger/jsonparser	v1.1.1	h1:2PnMjfWD7wBILjqQbt530v576A/cAbQvEW9gGIpYMUs=
dep	github.com/go-viper/mapstructure/v2	v2.0.0-alpha.1	h1:TQcrn6Wq+sKGkpyPvppOz99zsMBaUOKXq6HSv655U1c=
dep	github.com/gorilla/websocket	v1.5.1	h1:gmztn0JnHVt9JZquRuzLw3g4wouNVzKL15iLr/zn/QY=
dep	github.com/knadh/koanf/maps	v0.1.1	h1:G5TjmUh2D7G2YWf5SQQqSiHRJEjaicvU0KpypqB3NIs=
dep	github.com/knadh/koanf/providers/posflag	v0.1.0	h1:mKJlLrKPcAP7Ootf4pBZWJ6J+4wHYujwipe7Ie3qW6U=
dep	github.com/knadh/koanf/v2	v2.1.1	h1:/R8eXqasSTsmDCsAyYj+81Wteg8AqrV9CP6gvsTsOmM=
dep	github.com/mattn/go-colorable	v0.1.13	h1:fFA4WZxdEF4tXPZVKMLwD8oUnCTTo08duU7wxecdEvA=
dep	github.com/mattn/go-isatty	v0.0.20	h1:xfD0iDuEKnDkl03q4limB+vH+GxLEtL/jb4xVJSWWEY=
dep	github.com/mitchellh/copystructure	v1.2.0	h1:vpKXTN4ewci03Vljg/q9QvCGUDttBOGBIa15WveJJGw=
dep	github.com/mitchellh/reflectwalk	v1.0.2	h1:G2LzWKi524PWgd3mLHV8Y5k7s6XUvT0Gef6zxSIeXaQ=
dep	github.com/puzpuzpuz/xsync/v3	v3.1.0	h1:EewKT7/LNac5SLiEblJeUu8z5eERHrmRLnMQL2d7qX4=
dep	github.com/rs/zerolog	v1.32.0	h1:keLypqrlIjaFsbmJOBdB/qvyF8KEtCWHwobLp5l/mQ0=
dep	github.com/spf13/pflag	v1.0.5	h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=
dep	github.com/valyala/bytebufferpool	v1.0.0	h1:GqA5TC/0021Y/b9FG4Oi9Mr3q7XYx6KllzawFIhcdPw=
dep	golang.org/x/net	v0.25.0	h1:d/OCCoBEUq33pjydKrGQhw7IlUPI2Oylr+8qLx49kac=
dep	golang.org/x/sys	v0.20.0	h1:Od9JTbYCk261bKm4M/mw7AklTlFYIa0bIp9BgSm1S8Y=
build	-buildmode=exe
build	-compiler=gc
build	DefaultGODEBUG=asynctimerchan=1,gotypesalias=0,httplaxcontentlength=1,httpmuxgo121=1,httpservecontentkeepheaders=1,tls10server=1,tls3des=1,tlskyber=0,tlsrsakex=1,tlsunsafeekm=1,winreadlinkvolume=0,winsymlink=0,x509keypairleaf=0,x509negativeserial=1
build	CGO_ENABLED=1
build	CGO_CFLAGS=
build	CGO_CPPFLAGS=
build	CGO_CXXFLAGS=
build	CGO_LDFLAGS=
build	GOARCH=arm64
build	GOOS=darwin
build	GOARM64=v8.0
```

# Full error message
```
❯ bgpipe -o -- speaker :179
2024-08-26 10:45:53 INF listening on [::]:179 stage="[2] listen"
2024-08-26 10:45:55 INF connected [::1]:179 -> [::1]:62626 stage="[2] listen"
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/bgpfix/bgpfix/pipe.(*Line).Wait(...)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/line.go:83
github.com/bgpfix/bgpfix/pipe.(*Pipe).Wait(0x1400013c0e0)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/pipe.go:226 +0x48
github.com/bgpfix/bgpipe/core.(*Bgpipe).Run(0x14000146100)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/bgpipe.go:90 +0x1d0
main.main()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/main.go:15 +0x3c

goroutine 4 [chan receive]:
github.com/bgpfix/bgpfix/pipe.(*Input).process(0x1400012f098)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/input.go:160 +0x94
created by github.com/bgpfix/bgpfix/pipe.(*Line).start in goroutine 1
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/line.go:68 +0x3c

goroutine 5 [chan receive]:
github.com/bgpfix/bgpfix/pipe.(*Input).process(0x14000178200)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/input.go:160 +0x94
created by github.com/bgpfix/bgpfix/pipe.(*Line).start in goroutine 1
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/line.go:68 +0x3c

goroutine 6 [chan receive]:
github.com/bgpfix/bgpfix/pipe.(*Input).Wait(...)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/input.go:289
github.com/bgpfix/bgpfix/pipe.(*Line).start.func1()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/line.go:74 +0x54
created by github.com/bgpfix/bgpfix/pipe.(*Line).start in goroutine 1
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/line.go:72 +0xe0

goroutine 7 [chan receive]:
github.com/bgpfix/bgpfix/pipe.(*Input).process(0x1400012edd8)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/input.go:160 +0x94
created by github.com/bgpfix/bgpfix/pipe.(*Line).start in goroutine 1
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/line.go:68 +0x3c

goroutine 8 [chan receive]:
github.com/bgpfix/bgpfix/pipe.(*Input).process(0x14000178000)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/input.go:160 +0x94
created by github.com/bgpfix/bgpfix/pipe.(*Line).start in goroutine 1
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/line.go:68 +0x3c

goroutine 9 [chan receive]:
github.com/bgpfix/bgpfix/pipe.(*Input).Wait(...)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/input.go:289
github.com/bgpfix/bgpfix/pipe.(*Line).start.func1()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/line.go:74 +0x54
created by github.com/bgpfix/bgpfix/pipe.(*Line).start in goroutine 1
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/line.go:72 +0xe0

goroutine 10 [chan receive]:
github.com/bgpfix/bgpfix/pipe.(*Line).Wait(...)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/line.go:83
github.com/bgpfix/bgpfix/pipe.(*Pipe).Start.func1()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/pipe.go:175 +0x30
created by github.com/bgpfix/bgpfix/pipe.(*Pipe).Start in goroutine 1
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/pipe.go:174 +0xc4

goroutine 11 [chan receive]:
github.com/bgpfix/bgpfix/pipe.(*Pipe).eventHandler(0x1400013c0e0, 0x1400013c1a0)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/event.go:218 +0xc0
created by github.com/bgpfix/bgpfix/pipe.(*Pipe).Start in goroutine 1
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/pipe.go:182 +0x128

goroutine 12 [chan receive]:
github.com/bgpfix/bgpfix/pipe.(*Pipe).Start.func2()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/pipe.go:186 +0x38
created by github.com/bgpfix/bgpfix/pipe.(*Pipe).Start in goroutine 1
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/pipe.go:185 +0x168

goroutine 14 [chan receive]:
github.com/bgpfix/bgpipe/pkg/extio.(*Extio).WriteStream(0x1400016a500, {0x1027aafc0, 0x14000064090})
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/pkg/extio/extio.go:452 +0x44
github.com/bgpfix/bgpipe/stages.(*Stdout).Run(0x1400013c0e0?)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/stages/stdout.go:44 +0x30
github.com/bgpfix/bgpipe/core.(*StageBase).runStart.func2()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/run.go:69 +0x144
created by github.com/bgpfix/bgpipe/core.(*StageBase).runStart in goroutine 11
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/run.go:53 +0x354

goroutine 15 [select]:
github.com/bgpfix/bgpipe/stages.tcp_handle(0x14000114b60, {0x1027b0ab8, 0x14000064380}, 0x14000178200)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/stages/util.go:57 +0x368
github.com/bgpfix/bgpipe/stages.(*Listen).Run(0x1400013c0e0?)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/stages/listen.go:92 +0x30
github.com/bgpfix/bgpipe/core.(*StageBase).runStart.func2()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/run.go:69 +0x144
created by github.com/bgpfix/bgpipe/core.(*StageBase).runStart in goroutine 11
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/run.go:53 +0x354

goroutine 16 [chan receive]:
github.com/bgpfix/bgpipe/core.(*StageBase).Run(0x14000114820)
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/stage.go:108 +0x38
github.com/bgpfix/bgpipe/core.(*StageBase).runStart.func2()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/run.go:69 +0x144
created by github.com/bgpfix/bgpipe/core.(*StageBase).runStart in goroutine 11
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/run.go:53 +0x354

goroutine 33 [semacquire]:
sync.runtime_Semacquire(0x0?)
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/sema.go:71 +0x2c
sync.(*WaitGroup).Wait(0x140001461c0)
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/sync/waitgroup.go:118 +0x74
github.com/bgpfix/bgpipe/core.(*Bgpipe).Start.func1()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/bgpipe.go:112 +0x2c
created by github.com/bgpfix/bgpipe/core.(*Bgpipe).Start in goroutine 11
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/bgpipe.go:111 +0x5c

goroutine 34 [semacquire]:
sync.runtime_Semacquire(0x0?)
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/sema.go:71 +0x2c
sync.(*WaitGroup).Wait(0x140001461e0)
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/sync/waitgroup.go:118 +0x74
github.com/bgpfix/bgpipe/core.(*Bgpipe).Start.func2()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/bgpipe.go:117 +0x2c
created by github.com/bgpfix/bgpipe/core.(*Bgpipe).Start in goroutine 11
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/bgpipe.go:116 +0x9c

goroutine 36 [semacquire]:
sync.runtime_Semacquire(0x0?)
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/sema.go:71 +0x2c
sync.(*WaitGroup).Wait(0x140001461f0)
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/sync/waitgroup.go:118 +0x74
github.com/bgpfix/bgpipe/core.(*Bgpipe).Start.func4()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/bgpipe.go:129 +0x2c
created by github.com/bgpfix/bgpipe/core.(*Bgpipe).Start in goroutine 11
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/core/bgpipe.go:128 +0x11c

goroutine 50 [chan receive]:
github.com/bgpfix/bgpfix/pipe.(*Line).WriteTo(0x1029d36b0?, {0x1027ab680, 0x14000224008})
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpfix@v0.3.0/pipe/line.go:164 +0x70
io.copyBuffer({0x1027ab680, 0x14000224008}, {0x1027ab100, 0x1400012edc8}, {0x0, 0x0, 0x0})
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/io/io.go:411 +0x98
io.Copy(...)
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/io/io.go:388
net.genericReadFrom(0x14000160400?, {0x1027ab100, 0x1400012edc8})
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/net.go:762 +0x58
net.(*TCPConn).readFrom(0x14000064380, {0x1027ab100, 0x1400012edc8})
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/tcpsock_posix.go:54 +0x50
net.(*TCPConn).ReadFrom(0x14000064380, {0x1027ab100?, 0x1400012edc8?})
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/net/tcpsock.go:165 +0x30
github.com/bgpfix/bgpipe/stages.tcp_handle.func2()
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/stages/util.go:47 +0x84
created by github.com/bgpfix/bgpipe/stages.tcp_handle in goroutine 15
	/Users/sander/go/pkg/mod/github.com/bgpfix/bgpipe@v0.8.8/stages/util.go:45 +0x280
```

**Comment by pforemski** [comment]
Thanks for playing with bgpipe! I think the bug you found is because the TCP listen stage does not communicate to the speaker stage (which waits for an OPEN message, before possibly sending its own) that the connection was closed and there is no chance it will receive any messages at all.

This would be easier to fix if bgpipe was a monolith, but for the sake of flexibility and simplicity, I quickly fixed this in a6e4ac9 by simply stopping the listener after a (default) timeout of 1s. Solving this more accurately (no timeout) is probably possible, but I'd leave that as possible future work.

Could you please test the fix using `go install github.com/bgpfix/bgpipe@dccdf34` ?

**Comment by steffann** [comment]
That version at least shuts down cleanly:

```
❯ bgpipe -o -- speaker :179
2024-08-30 14:02:05 INF listening on [::]:179 stage="[2] listen"
2024-08-30 14:02:12 INF connected [::1]:179 -> [::1]:49761 stage="[2] listen"
2024-08-30 14:02:18 INF connection closed error=EOF read=0 stage="[2] listen" wrote=0
2024-08-30 14:02:18 ERR pipe error error="listen: EOF"
```

Just to be clear: it is expected that bgpipe only handles a single connection and then quits? I would have expected it to keep listening for new/multiple connections.

Cheers!

**Comment by pforemski** [comment]
Yes, at least for now that's the idea.

Longer term vision is to have another, parent process that would manage the
connections and pass the socket to child bgpipe processes when needed.
Whole bgpipe is meant for 1:1 bgp speakers, so there'll always be a need
for some sort of gatekeeper for 1:N scenario.

How does that sound to you? Happy to take feedback.

pt., 30 sie 2024, 14:04 użytkownik Sander Steffann ***@***.***>
napisał:

**Comment by steffann** [comment]
I understand. It’s a great tool! Thank you for writing it!
